import os
import whisper

def batch_transcribe():
    """
    Standalone script to scan student folders, transcribe audio files using Whisper,
    and save the results in a 'transcripts' folder.
    
    No external dependencies other than whisper.
    """
    # Get all student directories
    items = os.listdir(".")
    student_dirs = [d for d in items if os.path.isdir(d) and not d.startswith(".") and d not in ["__pycache__", ".venv"]]
    
    print(f"Found {len(student_dirs)} student directories.")
    
    # Load the Whisper model once at the beginning
    MODEL_NAME = "turbo"
    print(f"--- Loading Whisper model '{MODEL_NAME}' ---")
    model = whisper.load_model(MODEL_NAME)
    
    processed_count = 0
    skipped_count = 0

    for student_dir in student_dirs:
        # 1. Locate the audio in the presentation folder
        presentation_dir = os.path.join(student_dir, "presentation")
        if not os.path.exists(presentation_dir):
            presentation_dir = os.path.join(student_dir, "Presentation")
            if not os.path.exists(presentation_dir):
                continue
        
        # 2. Find the audio files generated by the batch_compress script
        audio_files = [f for f in os.listdir(presentation_dir) if f.lower().endswith("_audio.mp3")]
        
        if not audio_files:
            continue

        # 3. Ensure the 'transcripts' folder exists in the student directory
        transcript_dir = os.path.join(student_dir, "transcripts")
        if not os.path.exists(transcript_dir):
            os.makedirs(transcript_dir)
            print(f"\nProcessing Folder: {student_dir} (Created transcripts folder)")
        else:
            print(f"\nProcessing Folder: {student_dir}")

        for audio_file in audio_files:
            audio_path = os.path.join(presentation_dir, audio_file)
            # Remove '_audio.mp3' and keep the original video name
            base_name = audio_file.replace("_audio.mp3", "")
            output_file = os.path.join(transcript_dir, f"{base_name}.txt")
            
            # Skip if transcript already exists
            if os.path.exists(output_file):
                print(f"   >>> SKIPPING: {audio_file} (Transcript already exists)")
                skipped_count += 1
                continue
            
            print(f"   Transcribing: {audio_file} ...")
            try:
                # Transcribe directly using the loaded model
                result = model.transcribe(audio_path, verbose=False)
                
                # Save result to the transcripts folder
                with open(output_file, "w", encoding="utf-8") as f:
                    f.write(result["text"].strip())
                
                print(f"   Done! Saved to transcripts/{base_name}.txt")
                processed_count += 1
            except Exception as e:
                print(f"   Error transcribing {audio_file}: {e}")

    print(f"\n--- Transcription Summary ---")
    print(f"New transcripts created: {processed_count}")
    print(f"Transcripts skipped: {skipped_count}")
    print("Batch process complete!")

if __name__ == "__main__":
    batch_transcribe()
